spring:
  application:
    name: BackendForFrontend
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath*:graphql/**/
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template:
      default-topic: local-images-topic

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/database}
    username: ${SPRING_DATASOURCE_USERNAME:username}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          fetch_size: 100
        temp:
          use_jdbc_metadata_defaults: false

bff:
  api:
    image-service:
      timeout:
        connect: 100
        read: 100
      max-connections: 10
      url: ${IMAGE_SERVICE_URL:http://192.168.49.2:30082}