apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service-container
          imagePullPolicy: Never
          image: douglasmarq/auth-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.minikube.internal:5432/database"
            - name: SPRING_DATASOURCE_USERNAME
              value: "username"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SENDGRID_API_KEY
              value: "api_key"
            - name: EMAIL_SENDER
              value: "douglas.marq.alves@outlook.com"
